import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Header from "../components/Header";
import { GlobalContextProvider } from "../context/Store";

export const metadata = {
  title: "Welcome to MLA Sukanta Kumar Paul's Website",
  description:
    "Welcome to MLA Sukanta Kumar Paul's Website. Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
      <GlobalContextProvider>
        <Header />
        <div suppressHydrationWarning>{children}</div>
        <ToastContainer
          position="top-right"
          autoClose={1500}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover
          theme="light"
        />
      </GlobalContextProvider>
      </body>
    </html>
  );
}
